apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
  labels:
    name: apache
spec:
  replicas: 1
  template:
    metadata:
      name: apache
      labels:
        name: apache
        role: backend
    spec:
      containers:
      - name: apache
        image: docker.io/library/httpd:latest
        ports:
        - containerPort: 80
